load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test3",
    srcs = ["main.cc"],
    deps = [
        "//test_bazel/test3/lib1:lib1",
        "//test_bazel/test3/lib2:lib2"
        ]
)